# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 22:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='header',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='rules',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='choices',
            field=wagtail.wagtailcore.fields.StreamField([(b'question', wagtail.wagtailcore.blocks.CharBlock()), (b'choices', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('label', wagtail.wagtailcore.blocks.CharBlock(required=True))])))], default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
