# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 22:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_auto_20170620_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='choices',
            field=wagtail.wagtailcore.fields.StreamField([('options', wagtail.wagtailcore.blocks.StructBlock([(b'question', wagtail.wagtailcore.blocks.CharBlock()), (b'choices', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('label', wagtail.wagtailcore.blocks.CharBlock(required=True))])))]))]),
        ),
    ]
