# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_auto_20170620_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='choices',
            new_name='choice_list',
        ),
    ]
