# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0009_auto_20170620_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steppage',
            name='header',
        ),
    ]
