# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0011_steppagerelatedlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='rules',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
