# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0012_tasklist_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='rules',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='rule_list',
            field=wagtail.wagtailcore.fields.StreamField([('rules', wagtail.wagtailcore.blocks.StructBlock([('rule', wagtail.wagtailcore.blocks.CharBlock(default='')), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(default=None))], default=None))], default=None),
            preserve_default=False,
        ),
    ]
