# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:28
from __future__ import unicode_literals

from django.db import migrations
import roadmap.models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0015_auto_20170622_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='choice_rules',
            field=wagtail.wagtailcore.fields.StreamField([('rules', roadmap.models.ChoiceRulesBlock())]),
        ),
    ]
