# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0017_auto_20170622_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='choice_rules',
            field=wagtail.wagtailcore.fields.StreamField([('rules', wagtail.wagtailcore.blocks.StructBlock([('name', wagtail.wagtailcore.blocks.CharBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())]))]),
        ),
    ]
