# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:10
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0018_auto_20170622_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='choice_rules',
            field=wagtail.wagtailcore.fields.StreamField([('rules', wagtail.wagtailcore.blocks.StructBlock([('name', wagtail.wagtailcore.blocks.CharBlock()), ('pages', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock()))]))]),
        ),
    ]
