# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0022_auto_20170622_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='header',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
