# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0023_tasklist_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
