# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0024_tasklist_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='body',
        ),
    ]
