# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0025_remove_tasklist_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='isTemplateA',
            field=models.BooleanField(default=True),
        ),
    ]
