# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0029_roadmapfrequentlyaskedquestions_roadmaprelatedresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapfrequentlyaskedquestions',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasklistfrequentlyaskedquestions',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
