# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0030_auto_20170627_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steppage',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
