# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 21:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0034_tasklist_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='choice_list',
            field=wagtail.wagtailcore.fields.StreamField([('choices', wagtail.wagtailcore.blocks.StructBlock([(b'question', wagtail.wagtailcore.blocks.CharBlock()), (b'choices', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('label', wagtail.wagtailcore.blocks.CharBlock(required=True))], template='roadmap/content_blocks/choice_form.html')))]))]),
        ),
    ]
