# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0035_auto_20170628_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppage',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='steppage',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
