# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0036_auto_20170629_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='choice_list',
            field=wagtail.wagtailcore.fields.StreamField((('choices', wagtail.wagtailcore.blocks.StructBlock((('question', wagtail.wagtailcore.blocks.CharBlock()), ('choices', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock(required=True)),), template='roadmap/content_blocks/_choice_checkbox.html')))))),)),
        ),
    ]
