# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0037_auto_20170705_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='mrelief_link',
        ),
    ]
