# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:48
from __future__ import unicode_literals

from django.db import migrations
import roadmap.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0040_auto_20170710_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='views',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='choice_list',
            field=wagtail.wagtailcore.fields.StreamField((('question', wagtail.wagtailcore.blocks.CharBlock()), ('choices', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock(required=True)),), template='roadmap/content_blocks/_choice_checkbox.html')))), null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='rules',
            field=wagtail.wagtailcore.fields.StreamField((('name', roadmap.models.ChoiceRulesBlock()), ('pages', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock()))), null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='self_service_description',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='walk_through_description',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
        ),
    ]
