# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0041_auto_20170710_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='self_service_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='walk_through_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
