# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0043_auto_20170710_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='choice_list',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='choices',
            field=wagtail.wagtailcore.fields.StreamField((('label', wagtail.wagtailcore.blocks.CharBlock(required=True)),), null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='question',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
