# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0044_auto_20170710_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadmaprelatedresources',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='steppagerelatedresources',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='tasklistrelatedresources',
            old_name='description',
            new_name='short_description',
        ),
    ]
