# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0045_auto_20170710_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='isTemplateA',
            new_name='self_service_oriented_layout',
        ),
    ]
