# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0047_auto_20170712_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapfrequentlyaskedquestions',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='steppagefrequentlyaskedquestions',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='tasklistfrequentlyaskedquestions',
            name='page_url',
        ),
    ]
