# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0048_auto_20170712_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='has_strict_rules',
            field=models.BooleanField(default=False),
        ),
    ]
