# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0049_tasklist_has_strict_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='default_pages',
            field=wagtail.wagtailcore.fields.StreamField((('pages', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock(), required=False)),), blank=True),
        ),
    ]
