# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0051_auto_20170718_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='default_pages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
