# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:10
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0052_auto_20170718_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='default_pages',
            field=wagtail.wagtailcore.fields.StreamField((('page', wagtail.wagtailcore.blocks.PageChooserBlock()),), blank=True, default=[]),
        ),
    ]
