# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 18:58
from __future__ import unicode_literals

from django.db import migrations
import roadmap.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0053_auto_20170718_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='rules',
            field=wagtail.wagtailcore.fields.StreamField((('rule', wagtail.wagtailcore.blocks.StructBlock((('name', roadmap.models.ChoiceRulesBlock()), ('pages', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock())), ('override', wagtail.wagtailcore.blocks.BooleanBlock(default=False, required=False))))),), blank=True, default=[]),
        ),
    ]
