# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0057_tasklist_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='icon',
            field=models.CharField(blank=True, choices=[('icon-application', 'Application'), ('icon-education', 'Education'), ('icon-email', 'Email 1'), ('icon-email-2', 'Email 2'), ('icon-homeless', 'Homeless'), ('icon-house', 'House'), ('icon-job-center', 'Job Center'), ('icon-phone', 'Phone'), ('icon-resume', 'Resume'), ('icon-pencil', 'Pencil'), ('icon-happy', 'Happy face')], default='', max_length=255),
        ),
    ]
