# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0060_auto_20170816_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='icon',
        ),
    ]
