# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:31
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0065_auto_20170906_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='video',
            field=wagtail.wagtailcore.fields.StreamField((('video', wagtail.wagtailembeds.blocks.EmbedBlock(max_num=1)),), blank=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='sections',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('pages', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock())), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))))),)),
        ),
    ]
