# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0066_auto_20170907_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='video',
            field=wagtail.wagtailcore.fields.StreamField((('video', wagtail.wagtailcore.blocks.StreamBlock((('video', wagtail.wagtailembeds.blocks.EmbedBlock()),), max_num=1)),), blank=True),
        ),
    ]
