# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 00:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0067_auto_20170907_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='video',
            field=wagtail.wagtailcore.fields.StreamField((('video', wagtail.wagtailembeds.blocks.EmbedBlock()),), blank=True),
        ),
    ]
