# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0069_auto_20170907_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='self_service_description',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='self_service_oriented_layout',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='walk_through_description',
        ),
    ]
