# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0070_auto_20170908_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='message',
            field=models.CharField(default='Based on your choices we suggest looking at the following:', max_length=255),
        ),
    ]
