# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 18:53
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0071_tasklist_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppage',
            name='checklist_instructions',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
