# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('roadmap', '0073_auto_20170912_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Roadmap',
        ),
    ]
