# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0074_auto_20170912_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='nav_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
