# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0075_tasklist_nav_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='nav_title',
        ),
    ]
