# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0076_remove_tasklist_nav_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steppage',
            name='short_description',
            field=models.CharField(max_length=75),
        ),
    ]
