# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0077_auto_20170913_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='message',
            new_name='form_submission_message',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='body',
            new_name='page_body',
        ),
    ]
