# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0078_auto_20171002_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steppage',
            old_name='body',
            new_name='page_body',
        ),
    ]
