# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0079_auto_20171002_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='default_pages',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='default_steps',
            field=wagtail.wagtailcore.fields.StreamField((('page', wagtail.wagtailcore.blocks.PageChooserBlock()),), blank=True, default=[], help_text='The steps to show if someone submits a form with answers that are not covered by the rules'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, help_text='An address for where this person works', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='The name of someone to contact. Ex: Sharon Smith', max_length=255),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='form_submission_message',
            field=models.CharField(default='Based on your choices we suggest looking at the following:', help_text='The text that is shown to the user after they make a form submissiom', max_length=255),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='has_strict_rules',
            field=models.BooleanField(default=False, help_text='If the rule definitions are strict it will ONLY display results that match the exact answers (instead of the union of the answers)'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='page_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='The main content of the page, above the list of steps and form'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='question',
            field=models.CharField(blank=True, help_text='The question for the form on the page (optional)', max_length=255),
        ),
    ]
