# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_statement',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('pages', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.PageChooserBlock())), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))))),), blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.wagtailcore.fields.StreamField((('testimonial', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.CharBlock()), ('name', wagtail.wagtailcore.blocks.CharBlock())))),), blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
