# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170912_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='mission_statement',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
