# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 20:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170926_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
