# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='footer',
            new_name='website_footer',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='website_icon',
            new_name='website_header_icon',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='header',
            new_name='website_header_text',
        ),
    ]
